name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file docker-deployement-demo/Dockerfile --tag angular-app:$(date +%s)
  push_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        username: ${​​​​​​{​​​​​​ secrets.DOCKER_USERNAME }​​​​​​}​​​​​​
        password: ${​​​​​​{​​​​​​ secrets.DOCKERHUB_TOKEN }​​​​​​}​​​​​​
        repository: ${​​​​​​{​​​​​​ secrets.DOCKER_USERNAME }​​​​​​}​​​​​​/react-docker-dem
        tags: latest